"""Fresh Init with Finance

Revision ID: 828422e3942c
Revises: b51605236f93
Create Date: 2025-12-13 10:36:22.661134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828422e3942c'
down_revision: Union[str, Sequence[str], None] = 'b51605236f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_vendors_id'), 'finance_vendors', ['id'], unique=False)
    op.create_index(op.f('ix_finance_vendors_name'), 'finance_vendors', ['name'], unique=False)
    op.create_table('finance_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('extraction_status', sa.String(), nullable=True),
    sa.Column('audit_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['finance_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_invoices_id'), 'finance_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_finance_invoices_invoice_number'), 'finance_invoices', ['invoice_number'], unique=False)
    op.create_table('finance_audit_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['finance_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_audit_flags_id'), 'finance_audit_flags', ['id'], unique=False)
    op.create_table('finance_invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['finance_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_invoice_items_id'), 'finance_invoice_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_invoice_items_id'), table_name='finance_invoice_items')
    op.drop_table('finance_invoice_items')
    op.drop_index(op.f('ix_finance_audit_flags_id'), table_name='finance_audit_flags')
    op.drop_table('finance_audit_flags')
    op.drop_index(op.f('ix_finance_invoices_invoice_number'), table_name='finance_invoices')
    op.drop_index(op.f('ix_finance_invoices_id'), table_name='finance_invoices')
    op.drop_table('finance_invoices')
    op.drop_index(op.f('ix_finance_vendors_name'), table_name='finance_vendors')
    op.drop_index(op.f('ix_finance_vendors_id'), table_name='finance_vendors')
    op.drop_table('finance_vendors')
    # ### end Alembic commands ###
